-- ========================================================
-- Explore Pakur - Supabase PostgreSQL Schema
-- Run this script in Supabase SQL Editor:
-- https://supabase.com/dashboard/project/dmnyftahjdnrvjjcxxhq/sql
-- ========================================================

-- 1. Create tourist_spots table
CREATE TABLE IF NOT EXISTS public.tourist_spots (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  category TEXT NOT NULL, -- 'Waterfall', 'Cave & Hill', 'Thermal Spring', 'Park & Heritage'
  description TEXT NOT NULL,
  long_description TEXT,
  latitude NUMERIC(10, 6) NOT NULL,
  longitude NUMERIC(10, 6) NOT NULL,
  cover_image TEXT NOT NULL,
  header_image TEXT,
  gallery_images JSONB DEFAULT '[]'::jsonb,
  best_time_to_visit TEXT,
  distance_from_pakur_station TEXT,
  entry_fee TEXT,
  timing TEXT,
  nearest_railway TEXT,
  highlights JSONB DEFAULT '[]'::jsonb,
  cultural_note TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create visitor_reviews table
CREATE TABLE IF NOT EXISTS public.visitor_reviews (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  spot_id UUID REFERENCES public.tourist_spots(id) ON DELETE CASCADE,
  user_name TEXT NOT NULL,
  rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
  comment TEXT,
  visit_date TEXT,
  user_location TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Enable Row Level Security (RLS)
ALTER TABLE public.tourist_spots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.visitor_reviews ENABLE ROW LEVEL SECURITY;

-- 4. Create Policies: Public can Read, Admins can Insert/Update/Delete
CREATE POLICY "Allow public read access on tourist_spots"
  ON public.tourist_spots FOR SELECT
  USING (true);

CREATE POLICY "Allow full access for authenticated/service role on tourist_spots"
  ON public.tourist_spots FOR ALL
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Allow public read access on visitor_reviews"
  ON public.visitor_reviews FOR SELECT
  USING (true);

CREATE POLICY "Allow public insert access on visitor_reviews"
  ON public.visitor_reviews FOR INSERT
  WITH CHECK (true);

-- 5. Create index for fast slug lookups
CREATE INDEX IF NOT EXISTS idx_tourist_spots_slug ON public.tourist_spots(slug);
CREATE INDEX IF NOT EXISTS idx_tourist_spots_category ON public.tourist_spots(category);

-- 6. Pre-seed All 16 Pakur Destinations into Supabase
INSERT INTO public.tourist_spots (id, title, slug, category, description, long_description, latitude, longitude, cover_image, gallery_images, best_time_to_visit, distance_from_pakur_station, entry_fee, timing, nearest_railway, highlights, cultural_note)
VALUES
  ('31332747-fd02-4d26-9c4a-4f56e2c73e7d', 'Hiranpur Shiv Gufa & Forest Ashram', 'hiranpur-shiv-gufa-ashram', 'Cave & Hill', 'A serene forest rock cave sanctum near Hiranpur with ancient Shiva lingam and natural stone springs.', 'Nestled deep in the sal forests of Hiranpur, this natural basalt cave has been revered for generations. The cool subterranean chambers feature ancient rock-carved deities, secluded meditation points, and freshwater springs.', 24.615, 87.72, 'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&w=1200&q=80', '["https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&w=800&q=80"]'::jsonb, 'Oct to Mar', '21 km from Pakur HQ', 'Free Public Access', '06:00 AM - 06:00 PM', 'Pakur (PKR)', '["Ancient Cave Sanctum","Forest Ashram","Natural Basalt Formations"]'::jsonb, 'Annual gathering during Maha Shivratri draws thousands of pilgrims from across Santhal Pargana.'),
  ('a1b2c3d4-0001-4000-8000-000000000001', 'Singarsi Viewpoint', 'singarsi-viewpoint', 'Cave & Hill', 'Perched atop the Rajmahal Hill range, Singarsi offers breathtaking panoramic sunrises over lush Sal forests and indigenous Santhal settlements.', 'Singarsi Viewpoint sits within the ancient Rajmahal volcanic trap formations. Rising majestically above the plains of Pakur, it provides travelers with an unobstructed 360-degree vista of mist-laden valleys, rolling sal canopies, and traditional tribal hamlets. A hotspot for avid birdwatchers and landscape photographers, Singarsi comes alive in the winter mornings when clouds nestle beneath the hilltop peaks.', 24.582, 87.583, 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80', '["https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80","https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80","https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=800&q=80"]'::jsonb, 'Oct to Mar', '32 km from Pakur Railway Station', 'Free Public Entry', '05:30 AM � 05:30 PM', 'Pakur (PKR) / Barharwa (BHW)', '["Sunrise Panoramic View","Rajmahal Hill Formations","Tribal Trekking Routes","Sal Forest Canopy"]'::jsonb, 'Part of the ancestral lands inhabited by Sauria Paharia and Santhal communities with preserved folklore of hill spirits.'),
  ('a1b2c3d4-0002-4000-8000-000000000002', 'Kanchangarh Cave', 'kanchangarh-cave', 'Cave & Hill', 'An enigmatic natural basalt cavern hidden amidst dense woodland, revered in local folklore and surrounded by ancient rock formations.', 'Deep within the undulating terrain of Littipara block lies Kanchangarh Cave. Carved naturally through millenia of geological weathering in volcanic basalt, this cavern features dramatic rock crevices and cool internal chambers. Local villagers recount tales of spiritual ascetics who meditated within its peaceful sanctum.', 24.63, 87.62, 'https://ik.imagekit.io/r2h4n/explore-pakur/kinkakuji-temple-rokuon-ji-buddhist-temple-kyoto-japan-3840x2160-4319_ja_AT2HvC.jpg', '["https://ik.imagekit.io/r2h4n/explore-pakur/kinkakuji-temple-rokuon-ji-buddhist-temple-kyoto-japan-3840x2160-4319_d2-yC5x5y.jpg"]'::jsonb, 'Nov to Feb', '28 km from Pakur HQ', 'Free Public Entry', '06:00 AM � 04:30 PM', 'Pakur (PKR)', '["Natural Basalt Cave","Shaded Forest Walk","Historical Solitude","Geological Interest"]'::jsonb, 'Locally guarded sanctuary revered during Makar Sankranti and tribal festive ceremonies.'),
  ('a1b2c3d4-0003-4000-8000-000000000003', 'Lilatari Waterfall', 'lilatari-waterfall', 'Waterfall', 'A cascade plunging through verdant jungle gorges into crystal rock pools, creating a tranquil retreat during the post-monsoon months.', 'Fed by seasonal mountain streams originating in the uplands, Lilatari Waterfall cascades in multiple tiers over rugged granite boulders. The surrounding canopy of Mahua, Kendu, and Sal trees keeps the microclimate delightfully cool. It is Pakur''s prime destination for nature lovers seeking pristine, uncommercialized wilderness.', 24.61, 87.55, 'https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?auto=format&fit=crop&w=1200&q=80', '["https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?auto=format&fit=crop&w=800&q=80","https://images.unsplash.com/photo-1447752875215-b2761acb3c5d?auto=format&fit=crop&w=800&q=80"]'::jsonb, 'July to Jan', '38 km from Pakur Town', 'Free Public Entry', '06:00 AM � 05:00 PM', 'Pakur (PKR)', '["Multi-tiered Cascade","Lush Forest Gorge","Natural Swimming Basin","Post-Monsoon Flow"]'::jsonb, 'Surrounded by quiet Paharia settlements with rich herbal foraging traditions.'),
  ('a1b2c3d4-0004-4000-8000-000000000004', 'Dharni Pahar & Caves', 'dharni-pahar', 'Cave & Hill', 'An iconic granite hill complex with natural rock shelters, sacred cave shrines, and commanding views of the rural Pakur plateau.', 'Rising abruptly from the undulating agricultural plains, Dharni Pahar is a revered geological outcrop with wind-sculpted granite boulders. Pilgrims and nature enthusiasts ascend its ancient stone steps to visit the cave sanctum and take in sunsets over the Bansloi river valley.', 24.551, 87.721, 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80', '["https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80","https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80"]'::jsonb, 'Oct to Mar', '18 km from Pakur HQ', 'Free Public Entry', '05:00 AM � 06:30 PM', 'Pakur (PKR)', '["Rock-cut Cave Shrine","Sunset Viewpoint","Granite Bouldering","Annual Hill Fair"]'::jsonb, 'Focal point of regional gatherings during Shivratri where devotees climb the hill for prayers.'),
  ('a1b2c3d4-0005-4000-8000-000000000005', 'Sidho-Kanho Murmu Park', 'siddhu-kanhu-park', 'Park & Heritage', 'A premier municipal eco-park and monument honoring the heroic leaders of the 1855 Santhal Hul rebellion.', 'Named in tribute to the Santhal brothers Sidho and Kanho Murmu who spearheaded the legendary freedom uprising against British colonial oppression, this well-maintained eco-park features landscaped flower gardens, children''s play areas, illuminated walkways, and historical statues depicting regional tribal heritage.', 24.6292, 87.8385, 'https://images.unsplash.com/photo-1519331379826-f10be5486c6f?auto=format&fit=crop&w=1200&q=80', '["https://images.unsplash.com/photo-1519331379826-f10be5486c6f?auto=format&fit=crop&w=800&q=80"]'::jsonb, 'Round the year', '1.5 km from Pakur Station', '?10 per adult', '06:00 AM � 07:30 PM', 'Pakur (PKR)', '["Santhal Hul Monument","Musical Fountains","Botanical Flowerbeds","Family Picnic Lawns"]'::jsonb, 'Commemorative ceremonies and cultural festivals are held annually on Hul Diwas (June 30).'),
  ('a1b2c3d4-0006-4000-8000-000000000006', 'Sidpur (Taatloi) Hot Spring', 'sidpur-hot-spring', 'Thermal Spring', 'A naturally occurring geothermal sulphur spring bubbling amidst rural farmsteads, renowned for therapeutic mineral waters.', 'Located near the border of Pakur and Dumka districts along the riverbed, Sidpur (Taatloi) Hot Spring emits steaming, mineral-rich thermal water year-round. Pilgrims and visitors travel from across the Santhal Pargana division to bathe in the natural pools believed to soothe joint pain and skin ailments.', 24.582, 87.585, 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?auto=format&fit=crop&w=1200&q=80', '["https://images.unsplash.com/photo-1544161515-4ab6ce6db874?auto=format&fit=crop&w=800&q=80"]'::jsonb, 'Nov to Feb', '35 km from Pakur Station', 'Free Public Access', 'Open 24 Hours', 'Pakur (PKR)', '["Geothermal Mineral Water","Medicinal Sulphur Spring","Rural River Basin","Winter Bathing Spot"]'::jsonb, 'A traditional pilgrimage stop during Makar Sankranti where villagers prepare khichdi on the riverbanks.'),
  ('a1b2c3d4-0007-4000-8000-000000000007', 'Hiranpur Pargana Nadi (Bansloi River Ghat)', 'hiranpur-pargana-nadi', 'Waterfall', 'Scenic Bansloi river picnic banks and natural bathing ghat in Hiranpur, beloved for peaceful waters and winter family gatherings.', 'The Bansloi River flows gracefully past the Hiranpur plains, forming picturesque sandy banks, gentle rocky shallows, and lush riverside vegetation. Known locally as Pargana Nadi, this tranquil riverfront is Pakur''s favorite winter picnic destination, where families gather beneath leafy mango and sal groves for outdoor cooking, fishing, and relaxed riverside afternoons.', 24.588, 87.728, 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=1200&q=80', '["https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=800&q=80"]'::jsonb, 'Oct to Mar', '16 km from Pakur Railway Station', 'Free Public Access', '06:00 AM � 06:00 PM', 'Pakur (PKR)', '["Scenic Riverbed Picnic","Gentle Rocky Shallows","Bansloi Riverfront Walk","Family Day Out"]'::jsonb, 'Riverbanks serve as holy immersion sites during Chhath Puja and regional Santhal harvest celebrations.'),
  ('a1b2c3d4-0008-4000-8000-000000000008', 'Hiranpur Shill Durga Mandir', 'hiranpur-shill-durga-mandir', 'Park & Heritage', 'Revered spiritual hilltop temple perched upon ancient stone rocks in Hiranpur, famed for historic Durga Puja celebrations.', 'Resting gracefully on an elevated rock ridge in Hiranpur, the Shill Durga Mandir is a celebrated spiritual beacon in Pakur district. Built amidst natural boulder formations, the temple commands sweeping views of Hiranpur bazaar and rural green horizons. During the annual Sharadiya Durga Puja, thousands of devotees from across Jharkhand and Bengal assemble here for traditional prayers, cultural dramas, and temple fairs.', 24.575, 87.708, 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1200&q=80', '["https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=800&q=80"]'::jsonb, 'Round the year (Oct for Durga Puja)', '15 km from Pakur HQ', 'Free Darshan', '05:00 AM � 08:30 PM', 'Pakur (PKR)', '["Elevated Rock Shrine","Historic Durga Puja","Panoramic Countryside Views","Sacred Sanctum"]'::jsonb, 'Known for centuries-old community traditions and ceremonial evening aarti atop the hill ridge.'),
  ('a1b2c3d4-0009-4000-8000-000000000009', 'Martello Tower', 'martello-tower', 'Park & Heritage', 'An architectural landmark built in 1856 by the British Raj during the Santhal Hul rebellion, located in the heart of Pakur town.', 'Standing 30 feet tall with 30 key loopholes for musketry, the Pakur Martello Tower is a unique British defensive watchtower erected in 1856 by S.D.O. Sir Alexander Eden following the fierce Santhal Hul freedom uprising. Surrounded by heritage gardens, it serves as a tangible memorial to the turbulent colonial history of the Santhal Pargana.', 24.6344, 87.8475, 'https://images.unsplash.com/photo-1590059390046-24f1c9c4b789?auto=format&fit=crop&w=1200&q=80', '["https://images.unsplash.com/photo-1590059390046-24f1c9c4b789?auto=format&fit=crop&w=800&q=80"]'::jsonb, 'Round the year', '1 km from Pakur Station', 'Free Public Entry', '06:00 AM � 06:00 PM', 'Pakur (PKR)', '["Historic 1856 Watchtower","Santhal Hul Freedom History","British Colonial Architecture","Heritage Garden"]'::jsonb, 'A protected state heritage monument commemorating the valor of indigenous tribal freedom fighters.'),
  ('a1b2c3d4-0010-4000-8000-000000000010', 'Nityakali Mandir', 'nityakali-mandir', 'Park & Heritage', 'An ancient Kali temple with historic terracotta heritage and spiritual tranquility, revered by generations of devotees.', 'Nityakali Mandir is one of Pakur town''s oldest spiritual sanctuaries. Revered for its deep-rooted tantric and Shakta heritage, the temple features traditional Bengal-influenced terracotta craftsmanship and peaceful courtyard shrines under ancient banyan trees. Devotees visit during Kali Puja and Amavasya nights for sacred blessings.', 24.6385, 87.853, 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=1200&q=80', '["https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=800&q=80"]'::jsonb, 'Round the year', '2 km from Pakur Station', 'Free Entry', '05:00 AM � 09:00 PM', 'Pakur (PKR)', '["Terracotta Temple Art","Ancient Kali Sanctum","Diwali Kali Puja Celebrations","Quiet Courtyard"]'::jsonb, 'Believed to have been established by medieval zamindars who patronized classical Santhal Pargana temple art.'),
  ('a1b2c3d4-0011-4000-8000-000000000011', 'Maheshpur Rajbari Heritage Palace', 'maheshpur-rajbari', 'Park & Heritage', 'The historical royal palace estate of the Maheshpur Rajas featuring grand colonial arches, courtyards, and royal temples.', 'Located 30 km south of Pakur, Maheshpur was historically the seat of the illustrious Maheshpur Raj. The sprawling palace ruins feature magnificent archways, old durbar halls, vintage ponds, and ancient family temples. Walking through its regal corridors offers a glimpse into Santhal Pargana''s royal era.', 24.478, 87.765, 'https://images.unsplash.com/photo-1599839575945-a9e5af0c3fa5?auto=format&fit=crop&w=1200&q=80', '["https://images.unsplash.com/photo-1599839575945-a9e5af0c3fa5?auto=format&fit=crop&w=800&q=80"]'::jsonb, 'Oct to Mar', '30 km from Pakur HQ', 'Free Access', '07:00 AM � 05:30 PM', 'Pakur (PKR) / Murarai (MRR)', '["Royal Palace Ruins","Colonial Architectural Arches","Heritage Rajbari Pond","Historic Zamindari Estate"]'::jsonb, 'Maheshpur royals actively patronized regional education, classical arts, and indigenous craftsmen.'),
  ('a1b2c3d4-0012-4000-8000-000000000012', 'Singhashi Hilltop Peak & Shrine', 'singhashi-hilltop-peak', 'Cave & Hill', 'An elevated peak in the Rajmahal hills offering panoramic vistas across Pakur and natural rock crevices for hiking.', 'Singhashi Peak is one of the highest natural elevations in southern Pakur. Dense sal tree belts flank the winding ascent, which culminates at a hilltop rock sanctum offering 360-degree views of mist-covered ridges extending into the horizon. Popular among trekkers and adventure seekers.', 24.523, 87.654, 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80', '["https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80"]'::jsonb, 'Oct to Feb', '26 km from Pakur HQ', 'Free Entry', '06:00 AM � 05:00 PM', 'Pakur (PKR)', '["Panoramic Hill Trek","Untouched Forest Canopy","Summit Rock Shrine","Morning Cloud Inversion"]'::jsonb, 'Revered by local indigenous tribes who hold sacred ceremonies honoring forest guardians.'),
  ('a1b2c3d4-0013-4000-8000-000000000013', 'Hiranpur Weekly Haat & Tribal Craft Hub', 'hiranpur-craft-haat', 'Park & Heritage', 'The vibrant cultural pulse of rural Pakur, famous for authentic Santhal handlooms, indigenous stonecraft, and weekly haat vibes.', 'Every week, Hiranpur transforms into an energetic cultural mosaic. Artisans from surrounding tribal hamlets bring hand-carved black stone mortars, traditional bamboo baskets, colorful Santhal dhokra wraps, and forest produce. It is an unforgettable living slice of indigenous Jharkhand lifestyle.', 24.583, 87.712, 'https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&w=1200&q=80', '["https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&w=800&q=80"]'::jsonb, 'Weekly Haat Days (Tuesdays/Saturdays)', '15 km from Pakur Railway Station', 'Free Public Market', '08:00 AM � 06:00 PM', 'Pakur (PKR)', '["Authentic Tribal Haat","Handmade Black Stone Artifacts","Santhal Organic Produce","Cultural Immersion"]'::jsonb, 'An economic lifeline for hundreds of village families practicing centuries-old craft traditions.'),
  ('a1b2c3d4-0014-4000-8000-000000000014', 'Litipara Green Valley & Forest Reserve', 'litipara-eco-valley', 'Cave & Hill', 'Undulating emerald forest corridors, winding hill roads, and traditional tribal hamlets in the Littipara eco-belt.', 'Littipara represents the untamed green heart of Pakur. Characterized by winding ghat roads cutting through dense sal, teak, and mahua woodlands, this eco-valley offers pristine air, mountain streams, and authentic hospitality in traditional mud-and-thatch Santhal homes.', 24.692, 87.625, 'https://images.unsplash.com/photo-1447752875215-b2761acb3c5d?auto=format&fit=crop&w=1200&q=80', '["https://images.unsplash.com/photo-1447752875215-b2761acb3c5d?auto=format&fit=crop&w=800&q=80"]'::jsonb, 'July to Feb', '34 km from Pakur HQ', 'Free Access', 'Open daylight hours', 'Pakur (PKR)', '["Scenic Ghat Road Drive","Lush Sal Forest Canopy","Rural Village Tourism","Birdwatching Haven"]'::jsonb, 'Traditional Santhal mural art (Sohrai and Khovar patterns) adorns village walls throughout the valley.'),
  ('a1b2c3d4-0015-4000-8000-000000000015', 'Amrapara Forest Reserve & Stream Waterfall', 'amrapara-forest-waterfall', 'Waterfall', 'Pristine seasonal jungle streams and mini-cascades surrounded by ancient timber trees in the Amrapara plateau.', 'Tucked deep inside the south-western forest range of Pakur, Amrapara features sparkling hill streams that tumble over basalt boulders to form secluded forest cascades. A tranquil sanctuary away from commercial crowds, ideal for nature photography and meditation.', 24.512, 87.525, 'https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?auto=format&fit=crop&w=1200&q=80', '["https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?auto=format&fit=crop&w=800&q=80"]'::jsonb, 'Aug to Jan', '42 km from Pakur HQ', 'Free Entry', '06:30 AM � 04:30 PM', 'Pakur (PKR)', '["Hidden Forest Waterfall","Ancient Timber Woods","Cool Stream Pools","Pure Nature Trek"]'::jsonb, 'Guarded by regional Van Suraksha Samitis who maintain ecological harmony.')
ON CONFLICT (slug) DO NOTHING;
